apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 10
  template:
    spec:
      containers:
        - name: app-2
          image: odilontalk/sample-app:latest
          env:
          - name: ENV
            value: "prod-sa-1"
          - name: IDP_ENDPOINT
            value: "idp-prod"