apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-2
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: app-2
          image: odilontalk/sample-app:latest
          env:
          - name: ENV
            value: "homol"
          - name: IDP_ENDPOINT
            value: "idp-homol"