apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: sample-app-rollout
spec:
  template:
    metadata:
      labels:
        app: sample-app
        version: v1
    spec:
      containers:
        - name: sample-app
          image: quay.io/brancz/prometheus-example-app:v0.4.0
      analysis:
        args:
        - name: service-name
          value: "sample-app-canary.sample-app-lab-us-2.svc.cluster.local"

