apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: default-analysis-template
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: len(result) > 0 && result[0] >= 0.8
      # failureCondition: len(result) > 0 && result[0] < 0.8
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus.istio-system.svc.cluster.local:9090
          query: |
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}",response_code=~"2.*"}[1m]
            )) /
            sum(irate(
              istio_requests_total{reporter="source",destination_service=~"{{args.service-name}}"}[1m]
            ))
